# View pre-commit hooks at https://github.com/pre-commit/pre-commit-hooks#hooks-available
# !!!RUN pre-commit autoupdate!!! To get the latest versions. This gist has been collecting dust bunnies and cob webs.
# The commented repos/hooks will NOT autoupdate! If you're going to use them, uncomment and run pre-commit autoupdate.


default_stages: [commit, push]

fail_fast: true

minimum_pre_commit_version: '1.15.0'

exclude: 'migrations'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: destroyed-symlinks
    -   id: fix-byte-order-marker
    -   id: file-contents-sorter
    -   id: forbid-new-submodules
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]  # Preserve Markdown hard linebreaks
          #
    # Docformatter https://pypi.org/project/docformatter/
-   repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - --in-place
          - -r
          - --blank
          - --recursive
          - --wrap-summaries=72
          - --wrap-descriptions=72
          - --pre-summary-newline
          - --make-summary-multi-line

    # Add trailing commas https://github.com/asottile/add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

    # iSort https://pycqa.github.io/isort/
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args:
          - --trailing-comma
          - --use-parentheses
          - --balanced
          - --py=38
          - --profile=black
          - -l=79

    # Black https://black.readthedocs.io/en/stable/
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args:
          - --target-version=py38
          - --line-length=79


    # Unimport https://unimport.hakancelik.dev/#/
-   repo: https://github.com/hakancelik96/unimport
    rev: 1.2.0
    hooks:
    -   id: unimport
        args:
          - --remove
          - --include-star-import
          - --gitignore


    # Saftey https://pyup.io/safety/
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
    -   id: python-safety-dependencies-check
        files: pyproject.toml requirements.txt


    # Interrogate https://interrogate.readthedocs.io/en/latest/
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args:
          - --fail-under=95
          - --verbose
          - --ignore-init-method
          - --ignore-init-module
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
    -   id: add-trailing-comma
